### PR TITLE
Added Has and Replace

### PR DESCRIPTION
**Pull request by joshuaharmsen845**
Not sure if I did the markdown table records correctly, but the content is there.

### CODE REVIEW

**Review by ebrahimahmadi — APPROVED** [review]

**Comment by ebrahimahmadi** [comment]
@joshuaharmsen845 Thanks for your contribution.

**Comment by joshuaharmsen845** [comment]
> @joshuaharmsen845 Thanks for your contribution.

Of course! Could you please consider adding the hacktoberfest-accepted label to this PR so I could gain Hacktoberfest credit?

**Comment by ebrahimahmadi** [comment]
I did, please confirm that it did the job.

**Comment by joshuaharmsen845** [comment]
Yes, thank you!

**Pull request merged**
